# SmartFactory XAI — 슬라이드 생성 프롬프트 (본선 · 15분 · 화이트모드)

> **본선 제출**: 발표 자료 **PDF**(자유양식, 평가항목 전부 포함, **15분 분량**) + **MVP 시연영상 유튜브 링크**. 마감 5/22(금) 14:30.
> **분량 기준**: 15분 발표 → **약 20~22장** (장당 40~45초). 2차 선정 시 15분 발표 + 5분 Q&A.
> 사용법: 아래 **공통 스타일**을 모든 장에 적용 후, 장별 프롬프트를 Gamma/PowerPoint Copilot/HTML로 생성. **수치는 반드시 `슬라이드_데이터.md`(SSOT) 값만** 사용.

## 본선 평가 항목 (PDF에 전부 담겨야 함)
| 항목 | 배점 | 담는 슬라이드 |
|---|---|---|
| 문제 정의 (현장 문제 구체화 · 적용대상·목적) | 20 | 2·3 |
| AI 활용 (문제특성 적합성 · 실질 기여) | 25 | 5~15 |
| 플랫폼 기획 (기능 유기적 연결 · 데이터/사용자 흐름) | 20 | 6·18·19 |
| MVP 구현 완성도 (실제 구현·시연 가능) | 25 | 16·20·21 |
| 발표/전달력 (명확성·시간준수·Q&A) | 10 | 전체·22·Q&A |

---

## 공통 스타일 지침 (모든 슬라이드 공통) — 화이트(라이트) 모드

```
밝고 깔끔한 화이트 대시보드 톤. 배경 흰색(#FFFFFF), 섹션 카드 #F7F8FA + 옅은 테두리(#E5E7EB) + 약한 그림자.
크기는 16:9
본문 텍스트 짙은 회색(#1F2430), 보조 텍스트(#6B7280).
포인트 컬러(화이트 배경 대비 확보):
  - 시안/AI·정상 = #0091C2   - 레드/이상·위험 = #D42121   - 앰버/경고 = #D9820A
폰트: 한글 Pretendard 산세리프, 숫자는 모노스페이스 강조.
레이아웃: 좌상단 작은 라벨(eyebrow, 회색 대문자) → 큰 제목(짙은 색) → 콘텐츠. 여백 충분.
그리드/구분선 rgba(0,0,0,0.08). 표 헤더 옅은 회색 배경. 하단에 페이지번호+로고 작게.
금지: 정중앙 가리는 텍스트, 클립아트, 과한 그라데이션, 이모지 남발.
핵심 수치는 큰 모노 숫자 + 짧은 캡션. 슬라이드당 메시지 1개.
```

---

## [1] 표지
```
중앙 큰 제목 "SmartFactory XAI", 부제 "설명가능한 사출성형 통합 운영 플랫폼".
하단 한 줄: "불량을 터지기 전에 잡고, 왜 그런지까지 설명한다." + 팀명·날짜.
배경에 옅은 센서 격자/노드 라인 모티프(은은하게).
```

## [2] 문제 정의 — 제조 현장의 두 고통 `[문제정의]`
```
제목 "현장의 두 가지 문제". 좌우 2단 카드:
① 불량의 사후 발견 — "육안 검사 한계 → 다량 생산 후 적발 → 폐기·재작업 비용"(레드 아이콘)
② AI 블랙박스 — "왜 불량인지 설명 못 하면 현장이 안 믿고 안 움직인다"(레드 아이콘)
하단: "→ 사전 탐지 + 설명, 둘 다 필요하다".
```

## [3] 적용 대상 & 활용 목적 `[문제정의]`
```
제목 "누구를 위해, 무엇을 위해". 3칸:
- 적용 대상: 자동차 부품 사출성형 라인(KAMP cn7), 24개 공정 센서
- 사용자: 작업자 / 반장 / 부서장 (3계층)
- 활용 목적: 불량 사전 탐지 → 원인 설명 → 즉시 처방 → 4축(품질·설비·안전·생산) 운영
아이콘 + 한 줄씩.
```

## [4] 데이터 소개 — KAMP `[문제정의/AI활용]`
```
제목 "데이터 — KAMP 사출성형(cn7)". 중앙: 24센서를 5계열로 묶은 다이어그램
(시간·위치·속도·압력·온도, 각 계열 센서 개수 표기).
우측 큰 숫자: "검증 1,379샷 = 정상 1,340 + 불량 39", 그 아래 "불량률 ≈ 1%" 빨강 강조.
하단 작은 글씨: 라벨 cn7 6,736행 + 비라벨 운영 약 80만 행.
```

## [5] EDA ① — 정상은 모이고 불량은 튄다 `[AI활용]`
```
제목 "EDA ① 정상 vs 불량의 분포". 좌: 산점도/PCA 썸네일(정상 회색 군집 + 불량 빨강 외곽).
우 한 줄: "정상은 좁게 모이고 불량은 군집 밖으로 → '정상만 학습'하면 이상을 잡을 수 있다(이상탐지 신호)".
```

## [6] EDA ② — 센서는 사이클 순서로 연결된다 `[AI활용/플랫폼]`
```
제목 "EDA ② 공정 연쇄 상관". 중앙: 사출 사이클 순서대로 센서 노드를 잇는 작은 그래프,
강한 상관 엣지 라벨(예 사출압력↔형체결 r=0.99, 쿠션↔형개방 0.99).
하단: "→ 단일 센서가 아닌 연쇄 원인. 나중에 '인과 그래프'의 근거".
```

## [7] EDA ③ — 단위 제각각 → 표준화 `[AI활용]`
```
제목 "EDA ③ 스케일 불일치 → z-score". 좌: 센서별 범위 막대(온도 200~300, 시간 수초, 압력 수천) 대비.
우: "→ 각 센서를 '평소 대비 몇 σ'로 표준화. 큰 숫자 센서의 지배 방지".
작은 캡션: 불균형(불량1%) → 정확도 무의미 → 재현율·PR-AUC로 평가.
```

## [8] 핵심 발상 — 준지도 이상탐지 `[AI활용]` ★
```
제목 "발상의 전환 — 정상만 학습한다". 중앙 다이어그램:
[정상]→[오토인코더 압축/복원]→[복원 잘됨, 오차 작음(시안)]
[이상]→[같은 모델]→[복원 실패, 오차 큼(레드)]
하단 강조: "복원 오차 = 이상의 척도. 불량을 한 건도 안 봐도 잡는다."
```

## [9] 모델 아키텍처 `[AI활용/MVP]`
```
제목 "모델 구조". 중앙: 오토인코더 레이어 다이어그램 24→16→8→16→24 (8차원 병목 강조).
우측 박스: 베이스라인 3종(Isolation Forest·One-Class SVM·LOF)도 같은 정상 데이터로 학습.
하단 스펙: MSE 손실·Adam·조기종료, z-score 입력.
```

## [10] 임계값 τ 산출 `[AI활용]`
```
제목 "이상 판정 경계 τ". 수식 카드:
τ = (정상 복원오차 99분위 0.1225  +  F1 최적 0.5171) / 2 = 0.320
좌우 비교: "99분위=라벨없이(준지도) / F1최적=라벨사용 → 둘의 절충".
```

## [11] AI 판정 2단계 `[AI활용]` ★최핵심
```
제목 "AI는 어떻게 판정하나 — 2단계".
상단 [1단계 4-AI 합의]: AE·IF·OCSVM·LOF 4개 투표 아이콘 → "3개 이상 동의 = 이상".
하단 [2단계 강도 등급]: 복원오차/τ 비율 막대 — 1.5배 경고(앰버)/2.5배 위험/그 이상 긴급(레드).
한 줄: "판정 권한은 4-AI 합의에, 강도 눈금은 복원오차에".
```

## [12] 4-AI 합의 효과 `[AI활용]` ★
```
제목 "왜 4개인가 — 거짓경보를 줄인다". 막대 차트(슬라이드_데이터.consensus.fp):
≥1/4 FP 31 → ≥2/4 9 → ≥3/4 5 → ≥4/4 3. ≥3/4 막대만 시안 강조.
캡션: "정밀도 0.50 → 0.84. 한 모델이 틀려도 견고."
```

## [13] XAI ① — SHAP 원인 `[AI활용]`
```
제목 "왜 그런지 ① 원인 센서(SHAP)". 좌: 양의 SHAP 가로 막대(빨강, 큰 순) 썸네일.
우: "양의 SHAP = 복원오차를 키운 진짜 원인. 작업자가 손볼 센서 순위. (음수=반대 증거, 제외)".
```

## [14] XAI ② — 인과 그래프 `[AI활용]`
```
제목 "왜 그런지 ② 연쇄 원인(인과 그래프)". 중앙: 원인 센서 → 상류 공정 노드 연결,
엣지에 r 값. 캡션: "|r|≥0.4 + 사출 사이클 시간순서 충족 → 인과 추정. 단일 센서가 아닌 연쇄 파악".
```

## [15] XAI ③ — 자연어 보고서 `[AI활용]`
```
제목 "왜 그런지 ③ 자연어 처방(Claude Haiku)". 보고서 카드 3단:
원인: 최대 배압 +8.4σ … / 대처: HMI 배압 설정 확인, 노즐 점검 … / 리소스: 설비보전팀 호출 …
캡션: "작업자·반장·부서장 눈높이로 재작성. 바로 행동 가능".
```

## [16] 성능 — 믿을 만한가 `[MVP완성도]`
```
제목 "성능 — 검증 1,379샷". 큰 모노 숫자 가로: ROC-AUC 0.9254 · PR-AUC 0.708 · F1 0.732 · Recall 0.667.
우: 혼동행렬 2×2(TN1334·FP6·FN13·TP26, TN/TP=시안·FP/FN=레드).
하단: "성능 낮은 방식도 비교표에 공개 — 신뢰는 정직에서".
```

## [17] 정직성 — 모델의 한계 `[AI활용/발표]` ★차별점
```
제목 "우리는 약점도 화면으로 드러낸다". 좌: 계통별 불량 막대 — 온도 11건 1위 + "탐지율 0%" 큰 레드.
우: "온도불량 11건 중 AE 0·IF 4·OCSVM 2·LOF 1, 합의로 1건 — 4모델 전부 둔감(합의 풀어도 못 잡음).
온도는 정상도 변동 폭이 커서 편차가 묻힘."
하단 강조: "사각지대를 자동 진단 → 온도 전용 룰/SPC 보강. 자기 한계를 아는 AI가 더 안전하다".
```

## [17-B] AI 자가 개선 어드바이저 `[AI활용]` ★최대 차별점
```
제목 "AI가 스스로 약점을 메운다". 흐름 화살표:
사각지대 진단(온도 0%) → [🤖 AI 개선안 받기] → Claude가 평가
→ 개선안("온도 전용 분류기 + 4-AI OR 결합") + 실행 노트북(.ipynb)·계획서(.md) 다운로드.
하단 강조: "탐지 → 설명 → 자기 한계 진단 → 개선 코드 자동 생성. temperature 0으로 재현성 확보".
캡션(작게): "AI 제안·스타터 코드 — 실행·검증 후 채택".
```

## [18] 통합 플랫폼 — 4축 + 한 샷 동기화 `[플랫폼기획]` ★
```
제목 "하나의 엔진, 네 개의 시야". 2×2 카드(아이콘+한 줄):
품질(실시간 진단·원인·이력) / 설비(정비 우선순위·커버리지) / 안전(과열·과압·기계·위험매트릭스) / 생산(OEE·Pareto).
중앙 강조: "★ 실시간 진단에서 이상 샷 1개 선택 → 원인분석·안전 탭이 같은 샷으로 자동 동기화" (화살표로 연결).
하단: "같은 이상탐지 결과를 보는 사람·목적에 맞게 재해석".
```

## [19] 데이터 흐름 & 사용자 흐름 `[플랫폼기획]` ★
```
제목 "유기적으로 연결된 흐름". 상단 [데이터 흐름]: 센서 → z-score → 4-AI 판정 → SHAP·인과 → NLG → 4축(가로 플로우).
하단 [사용자 흐름]: 출근 ①실시간진단 → 경보 ②원인분석 → 안전위험 ⑤안전 → 마감 ⑥생산·③이력 → 주간 ④정비.
캡션: "데이터와 업무가 한 줄로 이어진다".
```

## [20] MVP 구현 — 기술 스택 `[MVP완성도]`
```
제목 "실제로 동작한다 — 목업 아님". 좌: 스택 아이콘(Next.js · FastAPI 실시간추론 · PyTorch AE · SHAP · Claude Haiku).
우: "모든 그래프가 검증 1,379샷 실측. 7개 화면이 단일 검증셋 기준으로 정합(ROC·혼동행렬·Pareto·커버리지 일치)".
작은 글씨: 값 없는 가동률·성능만 '가정' 태그 명시.
```

## [21] 라이브 데모 / 시연 영상 `[MVP완성도]`
```
제목 "MVP 시연". 대시보드 스크린샷 3컷 흐름:
① 실시간 진단 — 긴급, 4/4 발동, 복원오차 10×τ  ② 원인분석 — SHAP 1위 + 워터폴  ③ What-if — 슬라이더로 오차 하강.
하단 큰 박스: "▶ MVP 시연 영상" + 유튜브 링크/QR(제출 시 삽입). 캡션 "실제 모델 실시간 추론".
```

## [22] 마무리 & 기대효과 `[발표/전달력]`
```
제목 "설명할 수 있고, 정직한 AI". 4개 체크 포인트:
① 불량 1% 불균형 → 준지도 이상탐지  ② 4-AI 합의 → 거짓경보 31→5건
③ SHAP·인과·자연어 → 왜 그런지 설명  ④ 자기 한계까지 정직 공개
기대효과 한 줄: "불량 사전 차단 + 현장이 신뢰하고 행동하는 AI". 하단 팀명·감사.
```

---

## (PDF 부록 권장) Q&A 대비 슬라이드 — 발표엔 안 쓰고 PDF 뒤에 첨부
```
제목 "예상 질의 응답". 표로 7개 Q&A 요약(발표대본.md Q&A 그대로):
온도 한계 / 4-AI 필요성 / 합의 임계 / τ 산출 / OEE 가정 / 비라벨 80만 / SHAP 부호.
```

---

## 발표용 핵심 수치 치트시트 (슬라이드에 박을 값 — SSOT)
- 센서 24개 / 검증 1,379샷(정상 1,340 + 불량 39) / 불량률 ≈ 1%
- ROC-AUC **0.9254** · PR-AUC **0.708** · F1 **0.732** · Recall **0.667**(26/39) · Precision **0.813**(26/32)
- 혼동행렬 TN **1334** / FP **6** / FN **13** / TP **26**
- τ = **0.320** = (정상 99분위 0.1225 + F1최적 0.5171)/2
- 4-AI 거짓경보: ≥1/4 **31** → ≥3/4 **5**, 정밀도 0.50 → 0.84
- 온도 사각지대: 불량 11건 중 AE0/IF4/OCSVM2/LOF1, 합의 **1/11** (4모델 전부 둔감)
- 불량 Pareto: 금형온도4(11)·사출속도(10)·배압(8)·충전(8) = 누적 95%
- OEE: 양품률 97.17%(실측), 가동률·성능(가정)

> ⚠️ 위 값은 `슬라이드_데이터.md` / `results/slide_data.json`과 100% 일치. 임의 변경·반올림 금지.
